" enable syntax highlighting
syntax enable

set expandtab
set tabstop=2
set softtabstop=2
set shiftwidth=2

" expand tabs into spaces
"set expandtab

" show line numbers
set number

" set tabs to have 4 spaces
"set ts=4

" indent when moving to the next line while writing code
set autoindent

" when using the >> or << commands, shift lines by 4 spaces
"set shiftwidth=4

" show a visual line under the cursor's current line
" set cursorline

" show the matching part of the pair for [] {} and ()
set showmatch

" enable all Python syntax highlighting features
let python_highlight_all = 1

" set leader ,
let mapleader = ","

" Insert the escape with CTRL-V then ESC in insert mode
let @g = "Ofrom IPython import embed; embed(); raise ValueError()"

map <leader>b @g

" Map ctrl-j and ctrl-k
map <C-J> <C-W>j<C-W>_
map <C-K> <C-W>k<C-W>_
map <C-L> <C-W>l<C-W>_
map <C-H> <C-W>h<C-W>_

" Enable syntax highlighting
syntax enable 

" Default colorscheme
" This order matters - dark then default is ugly
colorscheme default
set background=dark

" Set utf8 as standard encoding and en_US as the standard language
set encoding=utf8

" Use Unix as the standard file type
set ffs=unix,dos,mac

" Simplify mappings for line completion and file completion
inoremap <C-l> <C-x><C-l>
inoremap <C-f> <C-x><C-f>
